import pandas as pd
import plotly.express as px

import plotly.graph_objects as go

channel_name = ["ADITHYA",
                "AEC",
                "AEC HD",
                "AFC",
                "AFC HD",
                "AJE",
                "AJE HD",
                "ANIMAX",
                "APL",
                "APL HD",
                "ARENA",
                "ARENA HD",
                "ART",
                "ASTRO SUPERSPORT2",
                "ASTRO SUPERSPORT3",
                "ASTRO SUPERSPORT4",
                "ASTRO SUPERSPORT",
                "ASTRO SUPERSPORT HD",
                "ASTRO SUPERSPORT2 HD",
                "ASTRO SUPERSPORT3 HD",
                "ASTRO SUPERSPORT4 HD",
                "AUSTRALIA PLUS",
                "AOD HD 350",
                "AOD 351",
                "AOD 352",
                "AOD 353",
                "AWANI",
                "AXN",
                "AXN HD",
                "BABY TV",
                "BBC",
                "BBC HD",
                "BEIN SPORTS",
                "BERNAMA",
                "BTV",
                "CCTV4",
                "CCTV4 HD",
                "CELESTIAL",
                "CELESTIAL CLASSIC",
                "CELESTIAL HD",
                "CERIA",
                "CERIA HD",
                "TVN HD",
                "CHUTTI",
                "CI",
                "CI HD",
                "CITRA",
                "CITRA HD",
                "CNBC",
                "CNN",
                "CNN HD",
                "CTI",
                "CGTN",
                "CTWK",
                "CTWK HD",
                "DISC",
                "DISC HD",
                "DISCOVERY ASIA",
                "DISN",
                "DISN HD",
                "DISNEY XD HD",
                "DJR",
                "DSCI",
                "DSCI HD",
                "ES",
                "ES HD",
                "FOOD NETWORK HD",
                "FOX ACTION HD",
                "FOX FAMILY HD",
                "FOX HD",
                "FOX SPORTS",
                "FOX SPORTS HD",
                "FOX SPORTS 2 HD",
                "FOX SPORTS 3 HD",
                "FOX SPORTS 2",
                "FOX SPORTS 3",
                "FOX MOVIES",
                "FOX MOVIES HD",
                "FOXLIFE",
                "FOXLIFE HD",
                "FX HD",
                "GOLF HD",
                "HBO",
                "HBO HD",
                "HELLO",
                "HGTV HD",
                "HIST",
                "HISTORY HD",
                "HITS HD",
                "HUA HEE DAI",
                "HUA HEE DAI HD",
                "KBS",
                "KBSW HD",
                "KIX HD",
                "MAKKAL",
                "MAX",
                "MAX HD",
                "MTV",
                "NAT GEO HD",
                "NAT GEO PEOPLE HD",
                "NAT GEO WILD",
                "NAT GEO WILD HD",
                "NAURA",
                "NGEO",
                "NHK",
                "NICK",
                "NICK HD",
                "OASIS",
                "OASIS HD",
                "OH!K HD",
                "ONE HD",
                "PRIMA",
                "PRIMA HD",
                "QUAN JIA HD",
                "RIA",
                "RIA HD",
                "SHX",
                "SHX HD",
                "SKY NEWS HD",
                "SM",
                "STAR VIJAY TV",
                "STAR VIJAY TV HD",
                "SUN-TV",
                "SUN-TV HD",
                "TLC",
                "TLC HD",
                "DMAX",
                "DMAX HD",
                "TUTOR TV PT3",
                "TUTOR TV SPM",
                "TUTOR TV UPSR",
                "TVBC",
                "TVBE",
                "TVBS",
                "TVBS HD",
                "TVIQ",
                "VAAN",
                "VINMEEN HD",
                "VT",
                "WARNA",
                "WARNA HD",
                "XHE",
                "XHE HD",
                "XTY",
                "XTY HD",
                "WLT HD",
                "OTHER-ASTRO"
                ]
all_ages = [795,
            943,
            708,
            332,
            1044,
            30,
            32,
            90,
            85,
            191,
            1928,
            782,
            617,
            228,
            215,
            128,
            205,
            843,
            857,
            384,
            456,
            23,
            419,
            161,
            105,
            36,
            1629,
            562,
            1942,
            597,
            53,
            30,
            371,
            819,
            0,
            565,
            279,
            162,
            2298,
            531,
            1131,
            2594,
            696,
            532,
            151,
            140,
            1380,
            2956,
            0,
            45,
            93,
            458,
            175,
            146,
            306,
            159,
            402,
            490,
            293,
            502,
            1931,
            441,
            89,
            243,
            57,
            131,
            870,
            1217,
            1132,
            1059,
            37,
            382,
            454,
            259,
            113,
            56,
            521,
            1259,
            262,
            962,
            98,
            19,
            558,
            1870,
            1796,
            277,
            124,
            277,
            726,
            115,
            529,
            376,
            540,
            1690,
            816,
            372,
            1248,
            161,
            363,
            1048,
            436,
            1847,
            2325,
            86,
            76,
            272,
            367,
            1613,
            2447,
            308,
            1297,
            2461,
            3664,
            638,
            1727,
            5221,
            112,
            134,
            27,
            1022,
            974,
            957,
            1033,
            977,
            319,
            1202,
            70,
            144,
            109,
            211,
            459,
            580,
            290,
            68,
            199,
            701,
            2224,
            1548,
            2190,
            1171,
            2893,
            83,
            256,
            686,
            308,
            426,
            7672
            ]
age_25_39 = [226,
             240,
             199,
             75,
             350,
             23,
             0,
             50,
             25,
             36,
             550,
             276,
             221,
             65,
             43,
             16,
             55,
             294,
             272,
             85,
             126,
             0,
             59,
             63,
             60,
             3,
             377,
             96,
             616,
             203,
             19,
             0,
             105,
             175,
             0,
             180,
             18,
             43,
             660,
             72,
             372,
             891,
             218,
             201,
             29,
             34,
             395,
             958,
             0,
             5,
             0,
             59,
             20,
             68,
             155,
             71,
             168,
             151,
             105,
             198,
             665,
             171,
             39,
             113,
             19,
             85,
             315,
             449,
             429,
             340,
             0,
             124,
             137,
             93,
             19,
             9,
             185,
             434,
             45,
             230,
             49,
             0,
             250,
             658,
             539,
             68,
             30,
             98,
             281,
             13,
             120,
             93,
             141,
             570,
             246,
             190,
             343,
             65,
             133,
             393,
             103,
             574,
             744,
             17,
             33,
             79,
             155,
             422,
             762,
             87,
             454,
             626,
             1203,
             80,
             537,
             1647,
             15,
             36,
             0,
             327,
             249,
             319,
             317,
             290,
             133,
             434,
             5,
             20,
             33,
             82,
             178,
             125,
             102,
             29,
             53,
             267,
             620,
             473,
             647,
             370,
             925,
             27,
             71,
             306,
             73,
             134,
             2263]


data = {'channel_name': channel_name,
        'all_ages': all_ages,
        'age_25_39': age_25_39
        }

df = pd.DataFrame(data, columns=["channel_name", "all_ages", "age_25_39"])

df["r_age"]=round(df["age_25_39"]/df["all_ages"],2)


print(df)



fig = px.bar_polar(df, r="r_age", theta="channel_name", template="plotly_dark")#color_discrete_sequence= px.colors.sequential.Plasma_r)
fig.show()

fig.write_html("graph_channel_plotly_dark.html")

# df = px.data.wind()
# fig = px.bar_polar(df, r="frequency", theta="direction",
#                    color="strength", template="plotly_dark",
#                    color_discrete_sequence= px.colors.sequential.Plasma_r)
# fig.show()
# fig = go.Figure()
#
# fig.add_trace(go.Barpolar(
#     r=[10,99,270,2527,230,2805,8],
#     name='Age 25-39'
# ))
# fig.add_trace(go.Barpolar(
#     r=[297,2043,2538,7123,732,5737,44],
#     name='All Ages'
#
# ))
#
#
#
# fig.update_traces(text=['No Formal Education', 'Primary', 'Lower Secondary', 'Middle Secondary', 'Upper Secondary', 'University/College', 'Not Disclosed'])
# fig.update_layout(
#     title='Education Level',
#     font_size=16,
#     legend_font_size=16
#
# )
# fig.show()
#
